# release: python manage.py migrate
web: gunicorn config.wsgi:application
{% if cookiecutter.use_celery == "y" -%}
worker: celery worker --app=config.celery_app --loglevel=info -f logs/celery.log
# beat: celery --app=config.celery_app beat -s /var/run/celerybeat-schedule --pidfile /celerybeat.pid
{%- endif %}
